version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.diffplug.gradle.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.9.0
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.dokka
    versions:
    - 1.4.20
    - 1.4.30
  - dependency-name: edu.wpi.first.GradleRIO
    versions:
    - 2021.2.1
    - 2021.2.2
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - 1.15.0
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
